# Generated by Django 2.2.4 on 2019-09-01 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecetasCategorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoReceta',
            fields=[
                ('idTipoReceta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('idUnidadesMedida', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUnidad', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('urlFoto', models.URLField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('vecesVista', models.IntegerField(blank=True, default=0)),
                ('vecesCompartida', models.IntegerField(blank=True, default=0)),
                ('numMeGusta', models.IntegerField(blank=True, default=0)),
                ('visible', models.BooleanField(blank=True, default=True)),
                ('costeReceta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('minutosTiempoPreparacion', models.IntegerField(blank=0, default=0)),
                ('idPropietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipoReceta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.TipoReceta')),
            ],
        ),
        migrations.CreateModel(
            name='PasosReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descPaso', models.TextField()),
                ('urlImagenPaso', models.URLField()),
                ('idReceta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.Receta')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPersonalizadaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLista', models.CharField(max_length=250)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('idUsuario', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('idReceta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.Receta')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.UnidadesMedida')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleListaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('numLista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.ListaPersonalizadaUsuario')),
                ('numReceta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.Receta')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(blank=True, default=True)),
                ('comentario', models.TextField()),
                ('idReceta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.Receta')),
                ('usuarioComentario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
