# Generated by Django 2.2.4 on 2019-08-29 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReceta',
            fields=[
                ('idTipoReceta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('idUnidadesMedida', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUnidad', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('urlFoto', models.URLField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('vecesVista', models.IntegerField(default=0)),
                ('vecesCompartida', models.IntegerField(default=0)),
                ('numMeGusta', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('idPropietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipoReceta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.TipoReceta')),
            ],
        ),
    ]
