# Generated by Django 2.2.4 on 2019-09-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_auto_20190901_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecetasCategorias',
        ),
    ]
