# Generated by Django 2.2.4 on 2019-09-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_categoriasreceta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriasReceta',
            new_name='CategoriasReceta2',
        ),
    ]
