# Generated by Django 2.2.4 on 2019-09-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_auto_20190901_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.Categorias')),
                ('idReceta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas.Receta')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriasReceta2',
        ),
    ]
